const ONE_DAY_SECONDS = 24 * 60 * 60
const SESSION_DAYS = 7

export const SESSION_COOKIE = 'memo_session'
export const SESSION_COOKIE_MAX_AGE_SECONDS = SESSION_DAYS * ONE_DAY_SECONDS
export const SESSION_TTL_MS = SESSION_DAYS * ONE_DAY_SECONDS * 1000
